// src/routes/liquidfollow/+page.svelte
<script>

</script>

<div id="liquid">
	<div class="bubble"></div>
</div>

<style>
	#liquid {
	height: 100%;
	width: 100%;

	position: fixed;
	bottom: 0px;

	overflow: hidden;
	pointer-events: none;
}

.bubble {
	position: absolute;
	left: 50%;
	top: 100%;

	height: max(300px, 30vw);
	width: max(300px, 30vw);

	background-color: blueviolet;
	border-radius: 100%;
	animation: wave 2s ease-in-out infinite;
}

@keyframes wave {

	from,
	to {
		transform: translate(-50%, 0%);
	}

	50% {
		transform: translate(-50%, -20%);
	}
}
</style>

// src/sites/liquidfollow.jsx
const LiquidFollow = () => {
	return <iframe
		id="content-iframe"
		title="Blob liquid follow"
		src="./liquidfollow/index.html"
		width="100%"
		height="100%"
		style={{
			position: 'fixed',
			top: '0px',
			bottom: '0px',
			width: '100%',
			border: 'none',
			margin: '0',
			padding: '0',
			overflow: 'hidden',
			height: '100%',
		}}>
	</iframe>
};

export default LiquidFollow;
