// src/App.svelte
<script>
	import { Router, Route, Link } from "svelte-routing";
	import Landing from './Landing.svelte';
	import Snowflakes from './Snowflakes.svelte';

	export let url = "";
</script>

<Router url="{url}">
	<nav>
		<Link to="/">Home</Link>
		<Link to="/snowflakes">Snowflakes</Link>
	</nav>
	<div>
		<Route path="/"><Landing/></Route>
		<Route path="/snowflakes"><Snowflakes/></Route>
	</div>
</Router>

<style>

</style>

// src/App.jsx
import './App.scss';
import { BrowserRouter, Route, Routes, Navigate } from "react-router-dom";
import Landing from "./landing/Landing";
import Snowflakes from "./snowflakes/Snowflakes";

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route>
          <Route path="*" element={<Navigate to="/" />} />
          <Route index element={<Landing />} />
          <Route path="snowflakes/" element={<Snowflakes />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default App;
